# Site settings
<<<<<<< HEAD
title: Агентство событий Екатерины Вержинской
description: "Доверьтесь профессионалам и получайте удовольствие от организации Вашего мероприятия!"
baseurl: "/main-site" # the subpath of your site, e.g. /blog
url: "http://verzhinskaya.ru" # the name of your domain
=======
title: Агентсво праздников
description: "A responsive Jekyll theme for dental clinics."
baseurl: "/main-site" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
>>>>>>> refs/remotes/origin/gh-pages
# logo_url: svg/min/logo.svg
# logo_url: img/logo.png

# Main
main:
    main_img: verzhinskaya-header.jpg
    main_title: Агентство событий Екатерины Вержинской
    main_description: Доверьтесь профессионалам и получайте удовольствие от организации Вашего мероприятия!

# Contact form
api_token: # Enter API token here

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax2.jpg

# Map
map:
    zoom: 17
    address: Memorialnyy park, Ufa, Russia
    address_details: svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/verzhinskaya
twitter: http://twitter.com
instagram: https://www.instagram.com/e.verzhinskaya/
youtube: http://youtube.com
skype: skype:verzhinskaya
vkontakte: https://vk.com/e.verzhinskaya
feed: yes

# Footer
copyright: © 2016 Агентство событий Екатерины Вержинской

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:

sass:
    sass_dir: _scss
    style: compressed
